# Generated by Django 5.2.6 on 2025-10-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria_imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('archivo', models.ImageField(default='imagenes/default.jpg', upload_to='imagenes/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
