# Generated by Django 5.2.5 on 2025-10-16 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria_imagenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(1, 'Positivo'), (-1, 'Negativo')])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='Galeria_imagenes.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'post')},
            },
        ),
    ]
