# Generated by Django 5.2.6 on 2025-10-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria_imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria_imagenes',
            name='archivo',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
